version: '3'

services:
  redis:
    image: redis:7.0
    volumes:
      - ./config/redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3
    ports:
      - "6379:6379"

  hca:
    image: hca # local image
    volumes:
      - ./config/app.prod.yaml:/app/config/app.yaml
      - ./config/proxy.prod.yaml:/app/config/proxy.yaml
    ports:
      - "5001:5001"
    environment:
      - APP_CONFIG_PATH=/app/config/app.yaml

  wsa:
    image: wsa # local image
    volumes:
      - ../webscanner-api/config/generator-tag-technologies.yaml:/app/config/generator-tag-technologies.yaml